name: Build and deploy PHP app to Azure Web App - proyectofinalcomputo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # ——————————————————————————————
      # 1) Eliminar archivos locales index.html / hostingstart.html (opcional)
      #    Esto evita que el ZIP que subiste contenga esos archivos en la raíz.
      - name: Eliminar index.html/hostingstart.html localmente
        run: |
          if [ -f index.html ]; then
            rm index.html
          fi
          if [ -f hostingstart.html ]; then
            rm hostingstart.html
          fi

      # ——————————————————————————————
      # 2) LOGIN A AZURE (Service Principal) — sin cambios
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C2CB8403D54242888F356002808D3281 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_421B31D9C18346E4A2B67A71F5292D58 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC019733DA55485382505E61E2DC5915 }}

      # ——————————————————————————————
      # 3) Obtener credenciales de publicación (Basic Auth) para Kudu API — NUEVO
      #    Esto nos da "publishingUserName" y "publishingPassword" codificados en Base64.
      - name: Get Kudu publishing credentials (Basic Auth)     # <<< NUEVO
        id: kudu_token                                        # <<< NUEVO
        run: |                                                 # <<< NUEVO
          # Obtenemos usuario y contraseña de publicación
          creds=$(az webapp deployment list-publishing-credentials \
                    --name proyectofinalcomputo \
                    --resource-group TuResourceGroup \
                    --query "[publishingUserName,publishingPassword]" \
                    --output tsv)                              # <<< NUEVO
          user=$(echo "$creds" | awk '{print $1}')             # <<< NUEVO
          pass=$(echo "$creds" | awk '{print $2}')             # <<< NUEVO
          basic=$(printf "%s:%s" "$user" "$pass" | base64)      # <<< NUEVO
          echo "::set-output name=BASIC_AUTH::$basic"           # <<< NUEVO

      # ——————————————————————————————
      # 4) Eliminar index.html/hostingstart.html en remoto usando Kudu API — NUEVO
      - name: Remove index.html/hostingstart.html via Kudu API  # <<< NUEVO
        run: |                                                 # <<< NUEVO
          kudu_basic=${{ steps.kudu_token.outputs.BASIC_AUTH }} # <<< NUEVO
          # Borramos index.html remoto (no falla si no existe)
          curl -X DELETE \
               -H "Authorization: Basic $kudu_basic" \
               "https://proyectofinalcomputo.scm.azurewebsites.net/api/vfs/site/wwwroot/index.html" || true
          # Borramos hostingstart.html remoto (no falla si no existe)
          curl -X DELETE \
               -H "Authorization: Basic $kudu_basic" \
               "https://proyectofinalcomputo.scm.azurewebsites.net/api/vfs/site/wwwroot/hostingstart.html" || true
        env:                                                   # <<< NUEVO
          AZURE_WEBAPP_NAME: proyectofinalcomputo               # <<< NUEVO

      # ——————————————————————————————
      # 5) Deploy del contenido sin index.html (ni hostingstart.html) — sin cambios
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'proyectofinalcomputo'
          slot-name: 'Production'
          package: .
